[package]
autoexamples = true
desription = "A simple linear algebra library for Rust."
edition = "2021"
license = "MIT"
name = "linalgz"
version = "0.1.0"

[dependencies]
num-complex = "0.4"
num-traits = "0.2"

[[example]]
name = "vector_ops"
